version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # Expose the Qdrant API on localhost:6333
    volumes:
      - qdrant_storage:/qdrant/storage # Persist data between container restarts
    restart: always # Ensure container restarts if it crashes

volumes:
  qdrant_storage: